### ISSUE TITLE
Refactor all roles to use local connection by default

### ISSUE THREAD

**Issue by dgarros** [Juniper/ravello-ansible#14]
Today all roles are implicitly expecting the playbook to run with in `connection: local` mode which can introduce some limitations if you want to have local and remote connections in the same playbook

I think it would be better to change all the roles to use local connection implicitly. 
It's possible to define that per task without loosing any functionality

Today
```yaml
  - name: Update VM in Application
      uri:
        url: "https://cloud.ravellosystems.com/api/v1/applications/{{ application_id }}/vms/{{ vm_id }}"
        method: PUT
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
```

Proposed change
```yaml
   - name: Update VM in Application
      local_action:
        module: uri
        url: "https://cloud.ravellosystems.com/api/v1/applications/{{ application_id }}/vms/{{ vm_id }}"
        method: PUT
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
```

The behavior is exactly the same and it's not required anymore to define `connection: local` in the playbook

I'll send a Pull Request for this change quickly
